### PR TITLE
Deb's Chai

### PR DESCRIPTION
**Pull request by debbhad**
Hey guys! Here's my recipe for Chai (tea)!

### CODE REVIEW

**Comment by JenniferRoubaud** [comment]
@debbhad please share some more details :)

**Comment by debbhad** [comment]
Chai = Tea
We just add milk and sugar to boiling tea leaves - its quite a staple back in India!

**Comment by JenniferRoubaud** [comment]
@debbhad great thank you for the details

**Comment by JenniferRoubaud** [comment]
:+1:

**Pull request merged**
