### PR TITLE
Create Nutella-Crepe-Special

### PR DESCRIPTION
**Pull request by nelson7787**

### CODE REVIEW

**Comment by JenniferRoubaud** [comment]
@nelson7787 Sounds yummy. what is special about it? Please share :)

**Comment by nelson7787** [comment]
@JenniferRoubaud the crepe batter is made with a can of beer! I'll add it

**Comment by NT01** [comment]
add another Enjoy! :+1:

**Comment by NT01** [comment]
add another enjoy! :+1:

**Comment by JenniferRoubaud** [comment]
:+1:

**Pull request merged**
